### PR TITLE
Fix progress when using VAD chunking

### LINKED ISSUE #151: VAD: Progress reporting doesn't report evenly when VAD is active
The updating of the `Progress` instance is not even when VAD is active. All the chunks complete around the same time, and so the progress jumps from 0 to 100% in the last moments (on the console - actually don't seem to see the Progress reported in the UI at all in this video).

v0.7.1
Platform: M1 Macbook Pro, 32 GB, Sonoma 14.5

Full Video: http://172.104.253.215/CleanShot-202024-05-28-20at-2013.37.44.mp4
File used: http://172.104.253.215/atp-2-min-clip.m4a

### PR DESCRIPTION
**Pull request by finnvoor**
Previously progress would jump around as the same progress object was used for every chunk. Now every chunk is added as a child progress with equal unit count.

fixes #151

### CODE REVIEW

**Comment by ZachNagengast** [comment]
This looks great, can you explain how the progress will look in the UI? In other words, on what event does the percentage increase? Maybe a video recording would help if you are able.

**Comment by finnvoor** [comment]
The progress update happens at the same time still, after each mel>encode>decode loop, but previously each transcribe task would go from 0->1 simultaneously, resulting in random updates.

Now each task is a child progress of the total progress, with an equal weighting, so the progress increases properly as each child progress goes from 0->1.

<details>
  <summary>Before</summary>

```
Progress: 0.440
Progress: 1.000
Progress: 0.427
Progress: 0.758
Progress: 1.000
Progress: 0.768
Progress: 1.000
Progress: 0.758
Progress: 0.829
Progress: 1.000
Progress: 0.924
Progress: 1.000
Progress: 0.867
Progress: 1.000
Progress: 0.853
Progress: 1.000
Progress: 0.787
Progress: 1.000
Progress: 0.720
Progress: 1.000
Progress: 0.711
Progress: 1.000
Progress: 0.741
Progress: 0.905
Progress: 1.000
Progress: 0.711
Progress: 0.967
Progress: 1.000
Progress: 0.768
Progress: 1.000
Progress: 0.933
Progress: 1.000
Progress: 1.143
Progress: 1.000
Progress: 1.175
Progress: 1.000
Progress: 0.711
Progress: 0.791
Progress: 1.000
Progress: 1.027
Progress: 1.000
Progress: 0.915
Progress: 1.000
Progress: 0.806
Progress: 1.000
Progress: 1.280
Progress: 1.000
Progress: 0.806
Progress: 1.000
Progress: 0.910
Progress: 1.000
Progress: 0.834
Progress: 1.000
Progress: 1.043
Progress: 1.156
Progress: 1.000
Progress: 0.981
Progress: 1.000
Progress: 0.908
Progress: 1.000
Progress: 1.109
Progress: 1.000
Progress: 0.806
Progress: 1.000
Progress: 0.948
Progress: 1.000
Progress: 0.924
Progress: 1.000
Progress: 1.081
Progress: 1.000
Progress: 1.009
Progress: 1.000
Progress: 1.090
Progress: 1.000
Progress: 1.261
Progress: 1.000
Progress: 1.172
Progress: 1.000
Progress: 1.137
Progress: 1.000
Progress: 1.081
Progress: 1.000
Progress: 0.900
Progress: 1.000
Progress: 1.043
Progress: 1.000
Progress: 1.308
Progress: 1.000
Progress: 1.303
Progress: 1.000
Progress: 1.090
Progress: 1.000
Progress: 1.327
Progress: 1.000
Progress: 1.332
Progress: 1.000
Progress: 1.303
Progress: 1.000
Progress: 0.943
Progress: 1.000
Progress: 1.318
Progress: 1.000
Progress: 1.275
Progress: 1.000
Progress: 1.389
Progress: 1.000
Progress: 1.351
Progress: 1.000
Progress: 1.192
Progress: 1.000
Progress: 1.357
Progress: 1.000
Progress: 1.398
Progress: 1.000
Progress: 1.313
Progress: 1.000
Progress: 1.370
Progress: 1.000
```
</details>

<details>
  <summary>After</summary>

```
Progress: 0.018
Progress: 0.027
Progress: 0.044
Progress: 0.045
Progress: 0.062
Progress: 0.077
Progress: 0.095
Progress: 0.112
Progress: 0.130
Progress: 0.147
Progress: 0.147
Progress: 0.165
Progress: 0.182
Progress: 0.199
Progress: 0.216
Progress: 0.216
Progress: 0.225
Progress: 0.228
Progress: 0.245
Progress: 0.246
Progress: 0.263
Progress: 0.280
Progress: 0.281
Progress: 0.288
Progress: 0.289
Progress: 0.306
Progress: 0.320
Progress: 0.321
Progress: 0.338
Progress: 0.338
Progress: 0.356
Progress: 0.356
Progress: 0.374
Progress: 0.387
Progress: 0.405
Progress: 0.422
Progress: 0.426
Progress: 0.444
Progress: 0.461
Progress: 0.479
Progress: 0.496
Progress: 0.496
Progress: 0.514
Progress: 0.532
Progress: 0.549
Progress: 0.549
Progress: 0.566
Progress: 0.567
Progress: 0.584
Progress: 0.584
Progress: 0.602
Progress: 0.619
Progress: 0.619
Progress: 0.637
Progress: 0.654
Progress: 0.671
Progress: 0.672
Progress: 0.689
Progress: 0.689
Progress: 0.707
Progress: 0.725
Progress: 0.742
Progress: 0.760
Progress: 0.777
Progress: 0.777
Progress: 0.795
Progress: 0.812
Progress: 0.830
Progress: 0.847
Progress: 0.851
Progress: 0.869
Progress: 0.886
Progress: 0.904
Progress: 0.921
Progress: 0.939
Progress: 0.939
Progress: 0.955
Progress: 0.972
Progress: 0.972
Progress: 0.981
Progress: 0.982
Progress: 1.000
```
</details>

**Comment by ZachNagengast** [comment]
For some reason watchos is timing out, could you try the simulator tests for watchos? I will update the timeout if those succeed locally

**Review by ZachNagengast — APPROVED** [review]
Approving pending tests passing

**Comment by finnvoor** [comment]
Not having any issues with the tests locally, the same test command passes. Not sure what the issue is with the CI.

**Comment by ZachNagengast** [comment]
Ok the errors are due to the simulator not booting fast enough, will update with a fix in a follow up PR that resolves #100

**Comment by ZachNagengast** [comment]
FYI just merged this https://github.com/argmaxinc/WhisperKit/pull/180 there seems to be an issue with the combine stuff on watchOS, so I limited the test to not run on that platform. Not sure whats causing it but its only happening on macOS 13 runners.

**Pull request merged**
