### PR TITLE
Regression Test Pipeline

### PR DESCRIPTION
**Pull request by Abhinay1997**
- [x] Add English text normlaization.
- [x] Add WER calculations.
- [x] Compare and check norm outputs from Python implementation
- [x] Add WER to the regression tests once #99 is merged

### CODE REVIEW

**Comment by Abhinay1997** [comment]
Code is still messy. Needs cleanup once the normalization starts working.

**Comment by Abhinay1997** [comment]
Running tests locally. Adding more unit tests for the new normalization code.

**Review by atiorh — CHANGES_REQUESTED** [review]
@Abhinay1997 As discussed offline, here are the last few items before we can merge this one:
- Removing example test result JSONs
- Removing the Fraction implementation altogether
- Adding AudioEncoder latency measurements to `LatencyStats`

We discussed the following as nice to haves (could defer to a future PR):

- Writing the following static attributes to the resulting JSON:
```
"static_attributes": 
- whisperkit_version (string)
- os (string)
- encoder_compute_units (string)
- decoder_compute_units (string)
- enable_word_timestamps (boolean)
- enable_eager_decoding (boolean)
- enable_vad (boolean)
- silence_threshold 
- is_low_power_mode (boolean)
- is_stream_simulated (boolean)
```

- Periodically (e.g. 1 minute) measuring the following stats in a separate thread and writing the timeseries results to the final JSON:
```json
"system_measurements":
- thermal_state (string)
- device_temperature (int)
- memory_total_available_gb (float)
- memory_total_used_gb (float)
- memory_app_allocated_gb (float)
- memory_app_used_gb (float)
- memory_swap_used_gb (float)
- battery_level (float)
- disk_total_space_gb (float)
- disk_free_space_gb (float)
```

**Comment by Abhinay1997** [comment]
@atiorh made the changes except for the `AudioEncoder` latency stats. Need to add a callback for that. Discussing with Zack on this.

**Pull request merged**
